### ISSUE TITLE
CRD update for aws-secret-operator

### ISSUE THREAD

**Issue by pgacek** [chatwork/charts#273]
Hi,
I've created the issue on the aws-secret-operator but maybe I should do it here.

I don't want to duplicate the content of issue - IMHO it's worth to update the CRD definition: 
https://github.com/chatwork/charts/blob/master/aws-secret-operator/crds/crd.yaml

to use the most recent one from the operator site:
https://github.com/mumoshu/aws-secret-operator/blob/main/deploy/crds/mumoshu.github.io_awssecrets.yaml

I checked manually - it works as described in the issue below:
https://github.com/mumoshu/aws-secret-operator/issues/63

https://github.com/chatwork/charts/pull/274

**Comment by cw-sakamoto** [comment]
https://github.com/chatwork/charts/pull/274
